[package]
name = "terminal_test_1"
version = "0.1.0"
authors = ["blito"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# UI
tui = "0.5"
termion = "1.5"

# JSON
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
